#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop bose.service >/dev/null
  systemctl disable bose.service || true
  rm /var/log/thingsplex/bose/* || true
fi