#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop bose.service >/dev/null
  systemctl disable bose.service || true
  rm -r /var/log/thingsplex/bose/ || true
  rm -r /opt/thingsplex/bose/data/ || true
fi